#!/bin/sh

autorun() {
	pgrep -x "$1" > /dev/null || "$@" &
}

start_dwm() {
	autorun dwmblocks
	export _JAVA_AWT_WM_NONREPARENTING=1
	while :; do
		dwm || break
	done
}

start_bspwm() {
	export _JAVA_AWT_WM_NONREPARENTING=1
	bspwm
}

setxkbmap -layout us,ru -option grp:alt_shift_toggle -option caps:ctrl_modifier
xset r rate 200 30

[ -f ~/.fehbg ] && ~/.fehbg &
#autorun easyeffects --gapplication-service
autorun xcompmgr
autorun dunst
autorun flameshot
autorun xautolock -time 10 -locker slock
autorun otd-daemon
autorun pcmanfm -d
#autorun qbittorrent

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in "/etc/X11/xinit/xinitrc.d"/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

start_bspwm
