#!/bin/sh

[ -f ~/.fehbg ] && ~/.fehbg || hsetroot -solid "#21252b" &
easyeffects --gapplication-service &
xcompmgr &
dwmblocks &
dunst &
flameshot &
xautolock -time 10 -locker slock &
sxhkd &
otd-daemon &
slskd &

while :; do
	_JAVA_AWT_WM_NONREPARENTING=1 ssh-agent dwm || break
done
