#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -a Space &

bspc monitor HDMI-0 -d A1 A2 A3 A4
bspc monitor DVI-D-0 -d B1 B2 B3 B4

killall polybar
polybar -c ~/.config/polybar/config.ini first &
polybar -c ~/.config/polybar/config.ini second &

bspc config border_width 2
bspc config window_gap   8

bspc config normal_border_color     "#4c566a"
bspc config active_border_color     "#4c566a"
bspc config focused_border_color    "#88c0d0"
bspc config presel_feedback_color   "#5e81ac"
bspc config split_ratio             0.55
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config honor_size_hints        true

bspc rule -a '*:*:buxn-gui' state=floating
bspc rule -a 'TelegramDesktop:Telegram:Media viewer' state=floating
bspc rule -a 'TelegramDesktop:Telegram:Просмотр медиа' state=floating
bspc rule -a mpv state=floating
bspc rule -a Nsxiv state=floating
bspc rule -a 'gajim:*:Password Required' state=floating
bspc rule -a easyeffects state=floating
bspc rule -a pavucontrol state=floating sticky=on
bspc rule -a st-256color:ncmpcpp state=floating sticky=on
bspc rule -a SimpleScreenRecorder state=floating sticky=on

bspc rule -a Screenkey manage=off
bspc rule -a dmenu manage=off
bspc rule -a slock manage=off
