#!/bin/sh

if pgrep -x sxhkd > /dev/null
	then killall -SIGUSR1 sxhkd
	else sxhkd -a Space &
fi

killall polybar
launch_polybar.sh

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 2
bspc config window_gap   8

bspc config normal_border_color     "#4c566a"
bspc config active_border_color     "#4c566a"
bspc config focused_border_color    "#88c0d0"
bspc config presel_feedback_color   "#5e81ac"
bspc config split_ratio             0.55
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config honor_size_hints        true

bspc rule -a '*:*:buxn-gui' state=floating
bspc rule -a 'TelegramDesktop:Telegram:Media viewer' state=floating
bspc rule -a 'TelegramDesktop:Telegram:Просмотр медиа' state=floating
bspc rule -a mpv state=floating
bspc rule -a Nsxiv state=floating
bspc rule -a 'gajim:*:Password Required' state=floating
bspc rule -a easyeffects state=floating
bspc rule -a pavucontrol state=floating sticky=on
bspc rule -a st-256color:ncmpcpp state=floating sticky=on
bspc rule -a SimpleScreenRecorder state=floating

bspc rule -a d1x-redux border=off center=on

bspc rule -a Screenkey manage=off
bspc rule -a dmenu manage=off
bspc rule -a slock manage=off
