directory: ~/music

plugins: convert

import:
  autotag: no
  move: yes

paths:
  default: '$albumartist/$album%aunique{}/$track $title'
  singleton: '$artist/$title%sunique{}'

convert:
  auto: no
  auto_keep: yes
  dest: /home/yorshex/musicopus
  format: opus
  formats:
    opus:
      command: opusenc '$source' '$dest'
      extension: opus
  never_convert_lossy_files: no
