#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export CLICOLOR=1
export HISTCONTROL=ignoreboth

[ -f /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

[ -f ~/.dir_colors ] && eval `dircolors ~/.dir_colors`

mkcd() { mkdir -p $1 && cd $1; }
emenv() { cd ~/software/emsdk; EMSDK_QUIET=1 source ./emsdk_env.sh; cd -; }
all-music() { mpc ls | mpc add; }
sa() { ssh-add ~/.ssh/"$1"; }
alias dash='PS1= dash'
alias sh='PS1= sh'
alias ls='ls -h --color=auto'
alias sl='ls'
alias grep='grep --color=auto'
alias diff='diff -u --color=auto'
alias mv='mv -i'
alias rm='rm -i'
alias nivm='nvim'
alias sxiv='nsxiv'
alias yt-dlp='yt-dlp --cookies-from-browser firefox'
alias yt-dlp-proxy='proxychains yt-dlp --cookies-from-browser firefox'
# uxn aliases
alias nasu='uxn11 ~/roms/nasu.rom'
alias drif='uxncli ~/roms/drifblim.rom'
alias uxnlin='uxncli ~/roms/uxnlin.rom'
alias uxnfor='uxncli ~/roms/uxnfor.rom'

bind 'set completion-ignore-case on'
bind 'set show-all-if-ambiguous on'
bind 'set colored-stats on'

__prompt_command() {
	local status="$?"
	local widget_user='\[\e[36m\]\u@\h'
	local widget_pwd='\[\e[32m\]\w'
	local widget_branch=''
	git status > /dev/null 2>&1
	local git_status="$?"
	[ "$git_status" -eq 0 ] && local widget_branch=' \[\e[0m\]('`git branch --show-current 2> /dev/null`')'
	local widget_dollar='\[\e[0m\]\$'
	[ "$status" -ne 0 ] && local widget_dollar='\[\e[1;31m\]\$'
	PS1="\n  ${widget_pwd}${widget_branch}\n${widget_dollar}\[\e[0m\] "
}

PROMPT_COMMAND=__prompt_command
