#!/usr/bin/env bash

export BEMOJI_PICKER_CMD='dmenu -l 20 -g 3 -i -F -fn Iosevka-15'
export SDL_SOUNDFONTS=/usr/share/soundfonts/default.sf2
export SOUND_FONT=/usr/share/soundfonts/default.sf2
export ANDROID_SDK_ROOT=/opt/android-sdk

export AWT_TOOLKIT=MToolKit

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export GOPATH="$XDG_STATE_HOME/go"

export NPM_CONFIG_USERCONFIG="$XDG_DATA_HOME/npm/npmrc"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WINEPREFIX="$XDG_DATA_HOME/wine"
export PARALLEL_HOME="$XDG_DATA_HOME/parallel"
export XAUTHORITY="$XDG_CONFIG_HOME/X11/Xauthority"
export XRESOURCES="$XDG_CONFIG_HOME/X11/Xresources"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export MIX_XDG=true

export HOST=`hostname`
export PS1='${PWD} \$ '

export LC_ALL=en_US.UTF-8

export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

export EDITOR=nvim

startx

[ "$SHELL" = /usr/bin/bash -a -f ~/.bashrc ] && . ~/.bashrc
